# Changes here will be overwritten by Copier
_commit: 0.14.2
_src_path: gh:bhklab/bhklab-project-template
author_email: bhklab.guanqiaofeng@gmail.com
author_full_name: Guanqiao Feng
github_username: guanqiaofeng
has_additional_authors: false
project_description: XevaDB project is a host for resources and code for xevadb paper
project_name: XevaDB Project
project_slug: xevadb-project
publish_to_github: true
python_version: '3.12'
repo_location: bhklab
